#!/bin/bash
#
# chkconfig: 345 99 1
# description: Alcove backup system
#

# Get function from functions library
. /etc/init.d/functions

# Start the service
start() {
        initlog -c "echo -n Starting Alcove server: "
        forever start /usr/share/alcove/app.js -a -l >(logger -t alcove-forever) -e >(logger -t alcove-forever) -o >(logger -t alcover-forever)
        ### Create the lock file ###
        touch /var/lock/subsys/alcove
        success $"Alcove server startup"
        echo
}

# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping Alcove server: "
        killproc alcove
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/alcove
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
